name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次，可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Sync with Upstream
      run: |
        git remote add upstream https://github.com/Loyalsoldier/clash-rules
        git fetch upstream
        git merge upstream/release  # 替换为你实际使用的分支
        git push origin release  # 替换为你实际使用的分支
